/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CareerTracksIndexRouteImport } from './routes/career-tracks.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResourcesUseCasesRouteImport } from './routes/resources.use-cases'
import { Route as ResourcesGuidesRouteImport } from './routes/resources.guides'
import { Route as ResourcesDirectoryRouteImport } from './routes/resources.directory'
import { Route as ResourcesCompareRouteImport } from './routes/resources.compare'
import { Route as ResourcesChangelogRouteImport } from './routes/resources.changelog'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInternshipsRouteImport } from './routes/dashboard.internships'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard.certificates'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CareerTracksSlugRouteImport } from './routes/career-tracks.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ResourcesBlogIndexRouteImport } from './routes/resources.blog.index'
import { Route as ResourcesBlogSlugRouteImport } from './routes/resources.blog.$slug'

const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTracksIndexRoute = CareerTracksIndexRouteImport.update({
  id: '/career-tracks/',
  path: '/career-tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResourcesUseCasesRoute = ResourcesUseCasesRouteImport.update({
  id: '/resources/use-cases',
  path: '/resources/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesGuidesRoute = ResourcesGuidesRouteImport.update({
  id: '/resources/guides',
  path: '/resources/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDirectoryRoute = ResourcesDirectoryRouteImport.update({
  id: '/resources/directory',
  path: '/resources/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCompareRoute = ResourcesCompareRouteImport.update({
  id: '/resources/compare',
  path: '/resources/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesChangelogRoute = ResourcesChangelogRouteImport.update({
  id: '/resources/changelog',
  path: '/resources/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInternshipsRoute = DashboardInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTracksSlugRoute = CareerTracksSlugRouteImport.update({
  id: '/career-tracks/$slug',
  path: '/career-tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ResourcesBlogIndexRoute = ResourcesBlogIndexRouteImport.update({
  id: '/resources/blog/',
  path: '/resources/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogSlugRoute = ResourcesBlogSlugRouteImport.update({
  id: '/resources/blog/$slug',
  path: '/resources/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/internships': typeof InternshipsRoute
  '/mentors': typeof MentorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/career-tracks/$slug': typeof CareerTracksSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/internships': typeof DashboardInternshipsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/resources/changelog': typeof ResourcesChangelogRoute
  '/resources/compare': typeof ResourcesCompareRoute
  '/resources/directory': typeof ResourcesDirectoryRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/use-cases': typeof ResourcesUseCasesRoute
  '/admin/': typeof AdminIndexRoute
  '/career-tracks/': typeof CareerTracksIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/blog/': typeof ResourcesBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/internships': typeof InternshipsRoute
  '/mentors': typeof MentorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/career-tracks/$slug': typeof CareerTracksSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/internships': typeof DashboardInternshipsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/resources/changelog': typeof ResourcesChangelogRoute
  '/resources/compare': typeof ResourcesCompareRoute
  '/resources/directory': typeof ResourcesDirectoryRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/use-cases': typeof ResourcesUseCasesRoute
  '/admin': typeof AdminIndexRoute
  '/career-tracks': typeof CareerTracksIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/blog': typeof ResourcesBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/internships': typeof InternshipsRoute
  '/mentors': typeof MentorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/career-tracks/$slug': typeof CareerTracksSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/internships': typeof DashboardInternshipsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/resources/changelog': typeof ResourcesChangelogRoute
  '/resources/compare': typeof ResourcesCompareRoute
  '/resources/directory': typeof ResourcesDirectoryRoute
  '/resources/guides': typeof ResourcesGuidesRoute
  '/resources/use-cases': typeof ResourcesUseCasesRoute
  '/admin/': typeof AdminIndexRoute
  '/career-tracks/': typeof CareerTracksIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/blog/': typeof ResourcesBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/internships'
    | '/mentors'
    | '/sitemap.xml'
    | '/success-stories'
    | '/admin/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/career-tracks/$slug'
    | '/courses/$slug'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/internships'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/resources/changelog'
    | '/resources/compare'
    | '/resources/directory'
    | '/resources/guides'
    | '/resources/use-cases'
    | '/admin/'
    | '/career-tracks/'
    | '/courses/'
    | '/dashboard/'
    | '/resources/blog/$slug'
    | '/resources/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/internships'
    | '/mentors'
    | '/sitemap.xml'
    | '/success-stories'
    | '/admin/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/career-tracks/$slug'
    | '/courses/$slug'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/internships'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/resources/changelog'
    | '/resources/compare'
    | '/resources/directory'
    | '/resources/guides'
    | '/resources/use-cases'
    | '/admin'
    | '/career-tracks'
    | '/courses'
    | '/dashboard'
    | '/resources/blog/$slug'
    | '/resources/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/internships'
    | '/mentors'
    | '/sitemap.xml'
    | '/success-stories'
    | '/admin/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/career-tracks/$slug'
    | '/courses/$slug'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/internships'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/resources/changelog'
    | '/resources/compare'
    | '/resources/directory'
    | '/resources/guides'
    | '/resources/use-cases'
    | '/admin/'
    | '/career-tracks/'
    | '/courses/'
    | '/dashboard/'
    | '/resources/blog/$slug'
    | '/resources/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InternshipsRoute: typeof InternshipsRoute
  MentorsRoute: typeof MentorsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  CareerTracksSlugRoute: typeof CareerTracksSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ResourcesChangelogRoute: typeof ResourcesChangelogRoute
  ResourcesCompareRoute: typeof ResourcesCompareRoute
  ResourcesDirectoryRoute: typeof ResourcesDirectoryRoute
  ResourcesGuidesRoute: typeof ResourcesGuidesRoute
  ResourcesUseCasesRoute: typeof ResourcesUseCasesRoute
  CareerTracksIndexRoute: typeof CareerTracksIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ResourcesBlogSlugRoute: typeof ResourcesBlogSlugRoute
  ResourcesBlogIndexRoute: typeof ResourcesBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-tracks/': {
      id: '/career-tracks/'
      path: '/career-tracks'
      fullPath: '/career-tracks/'
      preLoaderRoute: typeof CareerTracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resources/use-cases': {
      id: '/resources/use-cases'
      path: '/resources/use-cases'
      fullPath: '/resources/use-cases'
      preLoaderRoute: typeof ResourcesUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/guides': {
      id: '/resources/guides'
      path: '/resources/guides'
      fullPath: '/resources/guides'
      preLoaderRoute: typeof ResourcesGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/directory': {
      id: '/resources/directory'
      path: '/resources/directory'
      fullPath: '/resources/directory'
      preLoaderRoute: typeof ResourcesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/compare': {
      id: '/resources/compare'
      path: '/resources/compare'
      fullPath: '/resources/compare'
      preLoaderRoute: typeof ResourcesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/changelog': {
      id: '/resources/changelog'
      path: '/resources/changelog'
      fullPath: '/resources/changelog'
      preLoaderRoute: typeof ResourcesChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/internships': {
      id: '/dashboard/internships'
      path: '/internships'
      fullPath: '/dashboard/internships'
      preLoaderRoute: typeof DashboardInternshipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-tracks/$slug': {
      id: '/career-tracks/$slug'
      path: '/career-tracks/$slug'
      fullPath: '/career-tracks/$slug'
      preLoaderRoute: typeof CareerTracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resources/blog/': {
      id: '/resources/blog/'
      path: '/resources/blog'
      fullPath: '/resources/blog/'
      preLoaderRoute: typeof ResourcesBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blog/$slug': {
      id: '/resources/blog/$slug'
      path: '/resources/blog/$slug'
      fullPath: '/resources/blog/$slug'
      preLoaderRoute: typeof ResourcesBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardInternshipsRoute: typeof DashboardInternshipsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardInternshipsRoute: DashboardInternshipsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InternshipsRoute: InternshipsRoute,
  MentorsRoute: MentorsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  CareerTracksSlugRoute: CareerTracksSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ResourcesChangelogRoute: ResourcesChangelogRoute,
  ResourcesCompareRoute: ResourcesCompareRoute,
  ResourcesDirectoryRoute: ResourcesDirectoryRoute,
  ResourcesGuidesRoute: ResourcesGuidesRoute,
  ResourcesUseCasesRoute: ResourcesUseCasesRoute,
  CareerTracksIndexRoute: CareerTracksIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ResourcesBlogSlugRoute: ResourcesBlogSlugRoute,
  ResourcesBlogIndexRoute: ResourcesBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
